=== boschresearch/bcai_art/bcai_art/config_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "attack": {
            "additionalProperties": false,
            "properties": {
                "attack_type": {
                    "enum": [   "fgsm", "pgd",
                                "patch", "univ_perturb",
                                "frame_saliency",
                                "front_rev_simple",
                                "dummy" ] },
                "eps": { "type": "number" },
                "norm": { "enum": ["l1", "l2", "l3", "l4", "linf"] },
                "inner_attack": { "$ref": "#definitions/attack" },
                "add_arguments": { "type": "object"},
                "targets": {
                    "type": "array",
                    "items": { "type": "integer" }
                },
                "weights_file": { "type": "string" }
            },
            "required": [
                "attack_type"
            ],
            "type": "object"
        },
        "evaluator": {
            "additionalProperties": true,
            "properties": {
                "evaluator_name": { "type": "string" },
                "evaluator_type": {
                    "enum": [
                        "normal",
                        "attack",
                        "defense",
                        "randomized_smoothing",
                        "derandomized_smoothing",
                        "random_crops",
                        "random_crops_certification"
                    ],
                    "type": "string"
                },
                "attack": { "$ref": "#definitions/attack" },
                "add_arguments": { "type": "object"}
            },
            "required": [
                "evaluator_type",
                "evaluator_name"
            ],
            "type": "object"
        },
        "optimizer": {
            "properties": {
                "algorithm": {
                    "enum": [
                        "sgd",
                        "adam",
                        "rmsprop"
                    ],
                    "type": "string"
                },
                "init_lr":{ "type": "number" },
                "add_arguments": { "type": "object"},
                "scheduler":{ "$ref": "#definitions/scheduler" }
            },
            "required": [
                "algorithm",
                "init_lr"
            ],
            "type": "object"
        },
        "evaluation": {
            "additionalProperties": false,
            "properties": {
                "evaluators": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/evaluator" }
                },
                "eval_batch_size": {
                    "type": "integer",
                    "minimum": 1
                },
                "log_dir": { "type": "string" }
            },
            "required": [
                "evaluators",
                "eval_batch_size",
                "log_dir"
            ],
            "type": "object"
        },
        "trainer": {
            "additionalProperties": true,
            "properties": {
                "trainer_type": {
                    "enum": [
                        "normal",
                        "adv_fast",
                        "adv_free",
                        "adv_plug_attack",
                        "derandomized_smoothing",
                        "random_crops"
                    ],
                    "type": "string"
                },
                "train_model": { "type": "boolean" },
                "optimizer":{ "$ref": "#definitions/optimizer" },
                "train_attack": { "type": "boolean" },
                "attack": { "$ref": "#definitions/attack" },
                "attack_list" : {
                    "type": "array",
                    "items": {
                        "$ref": "#definitions/attack"
                    }
                },
                "snapshot_dir": { "type": "string" },
                "log_dir": { "type": "string" },
                "para_type": { "enum": [ "data", "attack", "independent" ] },
                "instance_qty": {
                    "type": "integer",
                    "minimum": 1
                },
                "batch_sync_step":{
                    "type": "integer",
                    "minimum": 1
                },
                "train_batch_size":{
                    "type": "integer",
                    "minimum": 1
                },
                "epoch_qty":{
                    "type": "integer",
                    "minimum": 1
                }
            },
            "required": [
                "trainer_type",
                "train_model",
                "epoch_qty",
                "train_batch_size",
                "batch_sync_step",
                "log_dir"
            ],
            "type": "object"
        },
        "training": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/trainer"
            }
        },
        "scheduler":{
            "additionalProperties": false,
            "properties":{
                "scheduler_type": { "type": "string" },
                "add_arguments": { "type": "object" }
            },
            "required":[
              "scheduler_type"
            ],
            "type": "object"
        },
        "dataset": {
            "additionalProperties": false,
            "properties": {
                "name": { "type": "string" },
                "root": { "type": "string" },
                "annot_file": {
                    "type": "array",
                    "items": { "type": "array", "items": { "type": "string" } }
                },
                "mean": {
                    "type": "array",
                    "items": { "type": "number" }
                },
                "std": {
                    "type": "array",
                    "items": { "type": "number" }
                },
                "add_arguments": {
                    "type": "object"
                }
            },
            "required": [
                "root",
                "name"
            ],
            "type": "object"
        },
        "model": {
            "additionalProperties": true,
            "properties": {
                "architecture": { "type": "string" },
                "weights_file": { "type": "string" },
                "add_arguments": { "type": "object" },
                "pretrained": { "type": "boolean" },
                "inner_model": { "$ref": "#/definitions/model" }
            },
            "required": [
                "architecture"
            ],
            "type": "object"
        },
        "device":{
            "additionalProperties": false,
            "properties":{
                "device_qty": { "type": "integer" },
                "device_name": { "type": "string" }
            },
            "type": "object"
        },
        "general": {
            "additionalProperties": false,
            "properties": {
                "device": {  "$ref": "#/definitions/device" },
                "num_data_workers": { "type": "integer" },
                "use_amp": { "type": "boolean" },
                "master_port": { "type": "integer" },
                "base_seed": { "type": "integer" },
                "dist_backend": { 
                    "enum":["gloo", "nccl", "mpi"], 
                    "type":"string"
                }
            },
            "required": [
                "device",
                "base_seed",
                "num_data_workers",
                "use_amp"
            ],
            "type": "object"
        }
    },
    "additionalProperties": false,
    "properties": {
        "_description": {
            "type": "string"
        },
        "evaluation": { "$ref": "#/definitions/evaluation" },
        "training": { "$ref": "#/definitions/training" },
        "dataset": { "$ref": "#/definitions/dataset" },
        "general":{ "$ref": "#/definitions/general" },
        "model": { "$ref": "#/definitions/model" }
    },
    "required": [
        "_description",
        "dataset",
        "model",
        "general",
        "training",
        "evaluation"
    ],
    "title": "JSON configuration",
    "type": "object"
}

=== boschresearch/bcai_art/sample_configs/resisc45/resisc45_patch.json
{
    "_description": "Patch training for RESISC-45 image classification",
    "general":{
        "device":{
            "device_qty": 1
        },
        "num_data_workers": 2,
        "use_amp": false,
        "master_port": 9999,
        "base_seed": 0 
    },
    "dataset": {
        "root": "data",
        "name": "resisc45"
    },
    "model":{
         "architecture": "densenet121",
         "pretrained": true,
         "weights_file": "sample_exper_dir/resisc45/normal/densenet121/train_model/snapshots/"
    },
    "training": [
        {
            "trainer_type": "adv_plug_attack",
            "train_model": true,
            "train_attack": true,
            "snapshot_dir": "sample_exper_dir/resisc45/adv_patch/densenet121/train_model/snapshots",
            "log_dir": "sample_exper_dir/resisc45/adv_patch/densenet121/train_model/logs",
            "para_type": "data",
            "train_batch_size": 32,
            "batch_sync_step": 64,
            "epoch_qty": 30,
            "attack": {
                "attack_type": "patch",
                "add_arguments": {
                    "alpha": 0.01,
                    "start": "random",
                    "scale_min": 0.1,
                    "scale_max": 0.25
                }
            },
            "optimizer": {
                "algorithm": "sgd",
                "init_lr": 0.00001,
                "add_arguments": {
                    "momentum": 0.9,
                    "weight_decay": 0.1
                },
                "scheduler": {
                    "scheduler_type": "one_cycle",
                    "add_arguments": {
                        "max_lr": 0.0001,
                        "pct_start": 0.3
                    }
                }
            }
        },
        {
            "trainer_type": "adv_plug_attack",
            "train_model": false,
            "train_attack": true,
            "snapshot_dir": "sample_exper_dir/resisc45/adv_patch/densenet121/train_attack/snapshots",
            "log_dir": "sample_exper_dir/resisc45/adv_patch/densenet121/train_attack/logs",
            "para_type": "independent",
            "instance_qty": 4,
            "train_batch_size": 24,
            "batch_sync_step": 64,
            "epoch_qty": 30,
            "attack": {
                "attack_type": "patch",
                "targets": [
                    27,
                    26,
                    7,
                    1
                ],
                "eps": 0.05,
                "norm": "linf",
                "add_arguments": {
                    "alpha": 0.01,
                    "start": "random",
                    "scale_min": 0.1
                }
            }
        }
    ],
    "evaluation" : {
        "log_dir": "sample_exper_dir/resisc45/adv_patch/densenet121/eval_model/logs",
        "eval_batch_size": 32,
        "evaluators": [
            {
                "evaluator_name": "normal",
                "evaluator_type": "normal"
            },
            {
                "evaluator_name": "patch 0",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "patch",
                    "weights_file": "sample_exper_dir/resisc45/adv_patch/densenet121/train_attack/snapshots/run0",
                    "eps" : 0.05,
                    "norm" : "linf",
                    "add_arguments" : {
                        "alpha" : 0.01,
                        "start" : "random",
                        "scale_min" : 0.1
                    }
                }
            },
            {
                "evaluator_name": "patch 1",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "patch",
                    "weights_file": "sample_exper_dir/resisc45/adv_patch/densenet121/train_attack/snapshots/run1",
                    "eps" : 0.05,
                    "norm" : "linf",
                    "add_arguments" : {
                        "alpha" : 0.01,
                        "start" : "random",
                        "scale_min" : 0.1
                    }
                }
            },
            {
                "evaluator_name": "patch 2",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "patch",
                    "weights_file": "sample_exper_dir/resisc45/adv_patch/densenet121/train_attack/snapshots/run2",
                    "eps" : 0.05,
                    "norm" : "linf",
                    "add_arguments" : {
                        "alpha" : 0.01,
                        "start" : "random",
                        "scale_min" : 0.1
                    }
                }
            },
            {
                "evaluator_name": "patch 3",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "patch",
                    "weights_file": "sample_exper_dir/resisc45/adv_patch/densenet121/train_attack/snapshots/run3",
                    "eps" : 0.05,
                    "norm" : "linf",
                    "add_arguments" : {
                        "alpha" : 0.01,
                        "start" : "random",
                        "scale_min" : 0.1
                    }
                }
            },
            {
                "evaluator_name": "pgd eps=0.031 steps=10",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type": "pgd",
                    "eps": 0.03,
                    "norm": "linf",
                    "add_arguments": {
                        "alpha": 0.01,
                        "num_iters": 10,
                        "restarts": 1,
                        "start": "random"
                    }
                }
            }
        ]
    }
}

=== boschresearch/bcai_art/sample_configs/cifar10/cifar10_normal_wideresnet.json
{
    "_description": "Standard training for CIFAR10 image classification (wide ResNet)",
    "general":{
        "device":{
          "device_qty": 1
        },
        "num_data_workers": 2,
        "use_amp": false,
        "master_port": 9999,
        "base_seed": 0 
    },
    "dataset": {
        "root": "datasets/cifar10",
        "name": "cifar10"
    },
    "model":{
        "architecture": "wideresnet28_20_cifar"
    },
    "training": [
        {
            "trainer_type": "normal",
            "snapshot_dir": "sample_exper_dir/cifar10/normal/wideresnet28_20_cifar/train_model/snapshots",
            "log_dir": "sample_exper_dir/cifar10/normal/wideresnet28_20_cifar/train_model/logs",
            "para_type": "data",
            "train_batch_size": 32,
            "epoch_qty": 50,
            "batch_sync_step": 8,
            "train_model": true,
            "optimizer": {
                "algorithm": "sgd",
                "init_lr": 0.001,
                "add_arguments": {
                    "momentum": 0.9,
                    "weight_decay": 0.256
                },
                "scheduler": {
                    "scheduler_type": "one_cycle",
                    "add_arguments": {
                        "max_lr": 0.00078,
                        "anneal_strategy": "linear",
                        "pct_start": 0.2
                    }
                }
            }
        }
    ],
    "evaluation" : {
        "log_dir": "sample_exper_dir/cifar10/normal/wideresnet28_20_cifar/eval_model/logs",
        "eval_batch_size": 32,
        "evaluators": [
            {
                "evaluator_name": "normal",
                "evaluator_type": "normal"
            }
        ]
    }
}

=== boschresearch/bcai_art/sample_configs/twosix_librispeech/sincnet_univ_perturb.json
{
    "_description": "Adversarial training (univ perturbation) for Librispeech speaker identification.",
    "general":{
        "device":{
            "device_qty": 4
        },
        "num_data_workers": 4,
        "use_amp": false,
        "master_port": 9999,
        "base_seed": 0 
    },
    "dataset": {
        "root": "",
        "name": "twosix_librispeech"
    },
    "model":{
         "architecture": "sincnet",
         "pretrained": false,
         "weights_file": "sample_exper_dir/twosix_librispeech/normal/sincnet/train_model/snapshots"
    },
    "training": [
        {
            "trainer_type": "adv_plug_attack",
            "train_model": true,
            "train_attack": true,
            "snapshot_dir": "sample_exper_dir/twosix_librispeech/univ_perturb/sincnet/train_model/snapshots",
            "log_dir": "sample_exper_dir/twosix_librispeech/univ_perturb/sincnet/train_model/logs",
            "para_type": "data",
            "train_batch_size": 512,
            "batch_sync_step": 32,
            "epoch_qty": 100,
            "attack": {
                "attack_type": "univ_perturb",
                "eps": 0.02,
                "norm": "linf",
                "add_arguments": {
                    "alpha": 0.001,
                    "start": "random"
                }
            },
            "optimizer": {
                "algorithm": "sgd",
                "init_lr": 0.00005,
                "add_arguments": {
                    "momentum": 0.9,
                    "weight_decay": 1e-5
                },
                "scheduler": {
                    "scheduler_type": "one_cycle",
                    "add_arguments": {
                        "max_lr": 0.0001,
                        "pct_start": 0.3
                    }
                }
            }
        },
        {
            "trainer_type": "adv_plug_attack",
            "train_model": false,
            "train_attack": true,
            "snapshot_dir": "sample_exper_dir/twosix_librispeech/univ_perturb/sincnet/train_attack/snapshots",
            "log_dir": "sample_exper_dir/twosix_librispeech/univ_perturb/sincnet/train_attack/logs",
            "para_type": "independent",
            "instance_qty": 4,
            "train_batch_size": 512,
            "batch_sync_step": 32,
            "epoch_qty": 25,
            "attack": {
                "attack_type": "univ_perturb",
                "targets": [22, 25, 15, 11],
                "eps": 0.02,
                "norm": "linf",
                "add_arguments": {
                    "alpha": 0.001,
                    "start": "random"
                }
            }
        }
    ],
   "evaluation" : {
        "log_dir": "sample_exper_dir/twosix_librispeech/normal/sincnet/eval_model/logs",
        "eval_batch_size": 64,
        "evaluators": [
            {
                "evaluator_name": "normal",
                "evaluator_type": "normal"
            }
        ]
    }
}

=== boschresearch/bcai_art/sample_configs/resisc45/resisc45_univ_perturb.json
{
    "_description": "Universal perturbation training for RESISC-45 image classification",
    "general":{
        "device":{
            "device_qty": 1
        },
        "num_data_workers": 2,
        "use_amp": false,
        "master_port": 9999,
        "base_seed": 0 
    },
    "dataset": {
        "root": "data",
        "name": "resisc45"
    },
    "model":{
         "architecture": "densenet121",
         "pretrained": true,
         "weights_file": "sample_exper_dir/resisc45/normal/densenet121/train_model/snapshots/"
    },
    "training":[
        {
            "trainer_type": "adv_plug_attack",
            "train_model": true,
            "train_attack": true,
            "snapshot_dir": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_model/snapshots",
            "log_dir": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_model/logs",
            "para_type": "data",
            "train_batch_size": 32,
            "batch_sync_step": 32,
            "epoch_qty": 30,
            "attack": {
                "attack_type": "univ_perturb",
                "eps": 0.031,
                "norm": "linf",
                "add_arguments": {
                    "alpha": 0.001,
                    "start": "random"
                }
            },
            "optimizer": {
                "algorithm": "sgd",
                "init_lr": 0.00001,
                "add_arguments": {
                    "momentum": 0.9,
                    "weight_decay": 0.1
                },
                "scheduler": {
                    "scheduler_type": "one_cycle",
                    "add_arguments": {
                        "max_lr": 0.0001,
                        "pct_start": 0.3
                    }
                }
            }
        },
        {
            "trainer_type": "adv_plug_attack",
            "train_model": false,
            "train_attack": true,
            "snapshot_dir": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_attack/snapshots",
            "log_dir": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_attack/logs",
            "para_type": "independent",
            "instance_qty": 4,
            "train_batch_size": 24,
            "batch_sync_step": 64,
            "epoch_qty": 30,
            "attack": {
                "attack_type": "univ_perturb",
                "targets": [27, 7, 8, 40],
                "eps": 0.031,
                "norm": "linf",
                "add_arguments": {
                    "alpha": 0.001,
                    "start": "random"
                }
            }
        }
    ],
    "evaluation" : {
        "log_dir": "sample_exper_dir/resisc45/univ_perturb/densenet121/eval_model/logs",
        "eval_batch_size": 32,
        "evaluators": [
            {
                "evaluator_name": "normal",
                "evaluator_type": "normal"
            },
            {
                "evaluator_name": "univ. perturbation 0",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "univ_perturb",
                    "weights_file": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_attack/snapshots/run0",
                    "eps" : 0.031,
                    "norm" : "linf"
                }
            },
            {
                "evaluator_name": "univ. perturbation 1",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "univ_perturb",
                    "weights_file": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_attack/snapshots/run1",
                    "eps" : 0.031,
                    "norm" : "linf"
                }
            },
            {
                "evaluator_name": "univ. perturbation 2",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "univ_perturb",
                    "weights_file": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_attack/snapshots/run2",
                    "eps" : 0.031,
                    "norm" : "linf"
                }
            },
            {
                "evaluator_name": "univ. perturbation 3",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type" : "univ_perturb",
                    "weights_file": "sample_exper_dir/resisc45/univ_perturb/densenet121/train_attack/snapshots/run1",
                    "eps" : 0.031,
                    "norm" : "linf"
                }
            },
            {
                "evaluator_name": "pgd eps=0.031 steps=10",
                "evaluator_type": "defense",
                "attack": {
                    "attack_type": "pgd",
                    "eps": 0.03,
                    "norm": "linf",
                    "add_arguments": {
                        "alpha": 0.01,
                        "num_iters": 10,
                        "restarts": 1,
                        "start": "random"
                    }
                }
            }
        ]
    }
}

=== boschresearch/bcai_art/sample_configs/so2sat/so2sat_normal_resnet18.json
{
    "_description": "Standard training for so2sat image classification",
    "general":{
        "device":{
          "device_qty": 4
        },
        "num_data_workers": 2,
        "use_amp": false,
        "master_port": 9999,
        "base_seed": 0 
    },
    "dataset": {
        "root": "/hdd2/datasets/so2sat_npz/",
        "name": "so2sat_npz"
    },
    "model":{
         "architecture": "resnet18_cifar",
         "add_arguments": { 
            "num_input_channels" : 14
         },
         "pretrained": true
    },
    "training": [
        {
            "trainer_type": "normal",
            "snapshot_dir": "sample_exper_dir/so2sat/normal/resnet18/train_model/snapshots",
            "log_dir": "sample_exper_dir/so2sat/normal/resnet18/train_model/logs",
            "para_type": "data",
            "train_batch_size": 512,
            "epoch_qty": 30,
            "batch_sync_step": 8,
            "train_model": true,
            "optimizer": {
                "algorithm": "sgd",
                "init_lr": 0.001,
                "add_arguments": {
                    "momentum": 0.9,
                    "weight_decay": 0.256
                },
                "scheduler": {
                    "scheduler_type": "one_cycle",
                    "add_arguments": {
                        "max_lr": 0.00078,
                        "anneal_strategy": "linear",
                        "pct_start": 0.2
                    }
                }
            }
        }
    ],
    "evaluation" : {
        "log_dir": "sample_exper_dir/so2sat/normal/resnet18/eval_model/logs",
        "eval_batch_size": 64,
        "evaluators": [
            {
                "evaluator_name": "normal",
                "evaluator_type": "normal"
            }
        ]
    }
}

=== boschresearch/bcai_art/sample_configs/mnist/mnist_free.json
{
    "_description": "PGD training for MNIST image classification",
    "general":{
        "device":{
            "device_qty": 1
        },
        "num_data_workers": 0,
        "use_amp": false,
        "master_port": 9999,
        "base_seed": 0 
    },
    "dataset": {
        "root": "datasets/mnist",
        "name": "mnist"
    },
    "model":{
         "architecture": "mnistnet",
         "pretrained": false,
         "weights_file": "sample_exper_dir/mnist/normal/mnistnet/train_model/snapshots/"
    },
    "training": [
        {
            "trainer_type": "adv_free",
            "train_model": true,
            "snapshot_dir": "sample_exper_dir/mnist/free/mnistnet/train_model/snapshots",
            "log_dir": "sample_exper_dir/mnist/free/mnistnet/train_model/logs",
            "para_type": "data",
            "train_batch_size": 512,
            "epoch_qty": 25,
            "batch_sync_step": 8,
            "eps": 0.2,
            "norm": "linf",
            "optimizer": {
                "algorithm": "sgd",
                "init_lr": 0.001,
                "add_arguments": {
                    "momentum": 0.9,
                    "weight_decay": 0.256
                },
                "scheduler": {
                    "scheduler_type": "one_cycle",
                    "add_arguments": {
                        "max_lr": 0.00078,
                        "anneal_strategy": "linear",
                        "pct_start": 0.2
                    }
                }
            }
        }
    ],
    "evaluation" : {
        "log_dir": "sample_exper_dir/mnist/free/mnistnet/eval_model/logs",
        "eval_batch_size": 64,
        "evaluators": [
            {
                "evaluator_name": "normal",
                "evaluator_type": "normal"
            },
            {
                "evaluator_name": "pgd eps=0.2 steps=10 (attack)",
                "evaluator_type": "attack",
                "add_arguments": {
                    "sample_qty" : 32
                },
                "attack": {
                    "attack_type": "pgd",
                    "eps": 0.2,
                    "norm": "linf",
                    "add_arguments": {
                        "alpha": 0.05,
                        "num_iters": 10,
                        "restarts": 1,
                        "start": "random"
                    }
                }
            }
        ]
    }
}
